### ISSUE TITLE
Where is parsing1.md?

### ISSUE THREAD

**Issue by jclsn** [rbtylee/tutorial-jsonc#1]
Was this file deleted by mistake?

**Comment by rbtylee** [comment]
I haven't worked on this in a long time, but I plan to return to it as soon as I finish the next release of Bodhi Linux. It has surprised me how popular this tutorial has got :) I have been having major health issues lately and am overrun with doctor visits and medical expenses. You can read about it on [Bodhi's forum](https://bodhilinux.boards.net/thread/1381/health-bodhi-linux-7).

As to this issue, parsing1.md [was deleted](https://github.com/rbtylee/tutorial-jsonc/commit/fbcb60bb322c8a7d5b42677242f13b9bd79f1c2e) and I think the content split amongst the rest of the files.

**Comment by jclsn** [comment]
Yeah no worries. I also got it without it. Very good tutorial. :) Get well soon!
